=begin
#AVM

#This is api for AVM (automated valuation machine)

The version of the AvmClient document: 1.0.0
Contact: info@enbisys.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.3

=end

require 'date'

module AvmClient
  class FloorLevel
    BASEMENT = "basement".freeze
    GROUND = "ground".freeze
    MIDDLE = "middle".freeze
    TOP = "top".freeze
    FLOOR_1 = "floor_1".freeze
    FLOOR_2 = "floor_2".freeze
    FLOOR_3 = "floor_3".freeze
    FLOOR_4 = "floor_4".freeze
    FLOOR_5 = "floor_5".freeze
    FLOOR_6 = "floor_6".freeze
    FLOOR_7 = "floor_7".freeze
    FLOOR_8 = "floor_8".freeze
    FLOOR_9 = "floor_9".freeze
    FLOOR_10 = "floor_10".freeze
    FLOOR_11 = "floor_11".freeze
    FLOOR_12 = "floor_12".freeze
    FLOOR_13 = "floor_13".freeze
    FLOOR_14 = "floor_14".freeze
    FLOOR_15 = "floor_15".freeze
    FLOOR_16 = "floor_16".freeze
    FLOOR_17 = "floor_17".freeze
    FLOOR_18 = "floor_18".freeze
    FLOOR_19 = "floor_19".freeze
    FLOOR_20 = "floor_20".freeze
    FLOOR_21_OR_ABOVE = "floor_21_or_above".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = FloorLevel.constants.select { |c| FloorLevel::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #FloorLevel" if constantValues.empty?
      value
    end
  end
end
