=begin
#AVM

#This is api for AVM (automated valuation machine)

The version of the AvmClient document: 1.0.0
Contact: info@enbisys.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.3

=end

require 'date'

module AvmClient
  class WallType
    CAVITY_WALL = "cavity_wall".freeze
    COB = "cob".freeze
    GRANITE_OR_WHIN = "granite_or_whin".freeze
    PARK_HOME_WALL = "park_home_wall".freeze
    SANDSTONE = "sandstone".freeze
    SOLID_BRICK = "solid_brick".freeze
    SYSTEM_BUILD = "system_build".freeze
    TIMBER_FRAME = "timber_frame".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = WallType.constants.select { |c| WallType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #WallType" if constantValues.empty?
      value
    end
  end
end
