=begin
#AVM

#This is api for AVM (automated valuation machine)

The version of the avm document: 1.0.0
Contact: info@enbisys.com
Generated by: https://openapi-generator.tech
avm Generator version: 4.0.3

=end

# Common files
require 'avm_client/avm_client'
require 'avm_client/avm_error'
require 'avm_client/version'
require 'avm_client/configuration'

# Models
require 'avm_client/models/additional_features'
require 'avm_client/models/built_form'
require 'avm_client/models/energy_efficiency'
require 'avm_client/models/energy_rating'
require 'avm_client/models/floor_level'
require 'avm_client/models/leasehold_or_freehold'
require 'avm_client/models/new_or_resale'
require 'avm_client/models/problem'
require 'avm_client/models/property_features'
require 'avm_client/models/property_type'
require 'avm_client/models/required_features'
require 'avm_client/models/roof_insulation'
require 'avm_client/models/roof_type'
require 'avm_client/models/valuation'
require 'avm_client/models/valuation_price_distribution'
require 'avm_client/models/wall_insulation'
require 'avm_client/models/wall_type'
require 'avm_client/models/window_glazing_type'

# APIs
require 'avm_client/api/default_api'

module AvmClient
  class << self
    # Customize default settings for the SDK using block.
    #     AvmClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
